debug:
	cd SharpKit.Compiler.Common && $(MAKE)
	cd SharpKit.Compiler.Java && $(MAKE)
	cd SharpKit.Compiler.Java.MsBuild && $(MAKE)
	cd SharpKit.Compiler.JavaScript && $(MAKE)
	cd SharpKit.Compiler.JavaScript.MsBuild && $(MAKE)
    
release:
	cd SharpKit.Compiler.Common && $(MAKE) release
	cd SharpKit.Compiler.Java && $(MAKE) release
	cd SharpKit.Compiler.Java.MsBuild && $(MAKE) release
	cd SharpKit.Compiler.JavaScript && $(MAKE) release
	cd SharpKit.Compiler.JavaScript.MsBuild && $(MAKE) release